### PR TITLE
Some simple fixes

### PR DESCRIPTION
**Pull request by bvssvni**
- Added `#![deny(missing_docs)]` crate attribute
- Fixed `cargo test` (doc tests)
- Use "```ignore" in docs when not type checked
- Make `as_any` default trait method
- Make `T` associated type on `Modulator` trait, since it mutates internal state

### CODE REVIEW

**Comment by bvssvni** [comment]
I also thought about making the modulators in "sources.rs" generic over float, but this can wait until num-traits has stabilized.

**Comment by bvssvni** [comment]
To explain why I changed from a generic parameter to an associated type: A generic parameter "for all" in Rust, which is used when a trait can be implemented more than one time. If the state of the modulator was external, this would be the right choice, but since the state is mutated within the modulator, the parameter can be made an associated type.

It does not limit the use case because e.g. `Wave<T>` can have more than one impl of `Modulator`: `impl Modulator for Wave<f32>` and `impl Modulator for Wave<f64>`

**Comment by apessino** [comment]
Hey! Great changes - thanks! I will merge and make a version 0.2.0 of the crate tomorrow. :)

**Review by apessino — COMMENTED** [review]
Hey!

I had made as_any a default trait method - unfortunately that prevents it from being called in the case where I need it, which is on trait objects as they are stored in the ModulatorEnv host, which is why I then just implemented it for each type. This change completely breaks the modulator play app, and makes it impossible to downcast from a trait object.

**Comment by bvssvni** [comment]
I've changed back `as_any`.

**Comment by apessino** [comment]
Cool - thanks! Will merge and update everything as soon as I have a moment. :)

**Pull request closed without merging**
